services:
  qgroundcontrol:
    image: t3gemstone/qgroundcontrol
    build:
      dockerfile: ./Dockerfile.qgroundcontrol
    hostname: qgroundcontrol
    privileged: true
    stdin_open: true
    tty: true
    environment:
      DISPLAY: "${DISPLAY}"
      QT_X11_NO_MITSHM: 1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
    device_cgroup_rules:
      - 'c *:* rmw'
    network_mode: host
    restart: always

  ardupilot-sitl:
    image: t3gemstone/ardupilot-sitl
    build:
      dockerfile: ./Dockerfile.ardupilot-sitl
    hostname: ardupilot-sitl
    stdin_open: true
    tty: true
    environment:
      AP_INSTANCE: "--instance 0"
      AP_SPEEDUP: "--speedup 1"
      AP_MODEL: "--model JSON"
      AP_VEHICLE: "--vehicle ${SITL_VEHICLE}"
      AP_FRAME: "--frame ${SITL_FRAME}"
      AP_LOCATION: "--location ${SITL_LOCATION}"
    network_mode: host
    restart: always

  gazebo:
    image: t3gemstone/gazebo
    build:
      dockerfile: ./Dockerfile.gazebo
    hostname: gazebo
    stdin_open: true
    tty: true
    environment:
      DISPLAY: "${DISPLAY}"
      QT_X11_NO_MITSHM: 1
      GZ_WORLD: ${SITL_WORLD}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
    device_cgroup_rules:
      - 'c *:* rmw'
    network_mode: host
    restart: always
