FROM ardupilot/ardupilot-dev-base

RUN apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    git \
    lsb-release \
    sudo \
    tzdata \
    && git config --global url."https://github.com/".insteadOf git://github.com/ \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir MAVProxy pymavlink

ARG UID=1000
ARG GID=1000
ARG USER=ap
ARG PWDR=/
RUN addgroup --gid ${GID} ${USER} \
    && adduser --gecos "ArduPilot User" --disabled-password --uid ${UID} --gid ${GID} ${USER} \
    && usermod -a -G dialout ${USER} \
    && echo ${USER}" ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/99_aptget \
    && chmod 0440 /etc/sudoers.d/99_aptget && chown root:root /etc/sudoers.d/99_aptget

ENV USER=${USER}
USER ${USER}

WORKDIR /home/${USER}/ardupilot
COPY --chown=${UID}:${GID} . .

RUN git submodule update --init --recursive

RUN ./waf distclean \
    && ./waf configure --board sitl \
    && ./waf copter \
    && ./waf plane \
    && ./waf rover \
    && ./waf sub

ENV AP_INSTANCE="--instance 0"
ENV AP_SPEEDUP="--speedup 1"
ENV AP_MODEL="--model JSON"
ENV AP_VEHICLE="--vehicle ArduPlane"
ENV AP_FRAME="--frame skywalker-x8-quad"
ENV AP_LOCATION="--location ARDUCOPTER_AUTOTEST"
ENV AP_PARAM=""

ENTRYPOINT ["sh", "-c", "Tools/autotest/sim_vehicle.py \
    --wipe-eeprom \
    --no-rebuild \
    --no-mavproxy \
    --sitl-instance-args --serial0=udpclient:127.0.0.1:14550 \
    ${AP_INSTANCE} \
    ${AP_SPEEDUP} \
    ${AP_MODEL} \
    ${AP_VEHICLE} \
    ${AP_FRAME} \
    ${AP_LOCATION} \
    ${AP_PARAM}"]
