services:
  qgroundcontrol:
    image: t3gemstone/qgroundcontrol
    build:
      context: ./qgroundcontrol
    hostname: qgroundcontrol
    privileged: true
    stdin_open: true
    tty: true
    environment:
      DISPLAY: "${DISPLAY}"
      QT_X11_NO_MITSHM: 1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
    device_cgroup_rules:
      - 'c *:* rmw'
    network_mode: host
    restart: always

  ardupilot-sitl:
    image: t3gemstone/ardupilot-sitl
    build:
      context: ./ardupilot-sitl
    hostname: ardupilot-sitl
    stdin_open: true
    tty: true
    environment:
      AP_INSTANCE: "--instance 0"
      AP_SPEEDUP: "--speedup 1"
      AP_MODEL: "--model JSON"
      AP_FRAME: "${SITL_FRAME}"
      AP_LOCATION: "${SITL_LOCATION}"
      AP_VEHICLE: "${SITL_VEHICLE}"
      AP_PARAM: "${SITL_PARAM}"
    network_mode: host
    restart: always

  gazebo:
    image: t3gemstone/gazebo
    build:
      context: ./gazebo
    hostname: gazebo
    stdin_open: true
    tty: true
    environment:
      DISPLAY: "${DISPLAY}"
      QT_X11_NO_MITSHM: 1
      GZ_WORLD: ${SITL_WORLD}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
    device_cgroup_rules:
      - 'c *:* rmw'
    network_mode: host
    restart: always
